name: Publish on GitHub Pages

on:
  workflow_dispatch: {}
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Compile
      run: make
    - name: Prepare deploy folder
      run: mkdir -p deploy
    - name: Move PDF to deploy folder
      run: cp documents/*.pdf deploy/
    - name: Prpare simple html
      run: |
        echo '<!DOCTYPE html>' > deploy/index.html
        echo '<html lang="en">' >> deploy/index.html
        echo '<head><meta charset="UTF-8"><title>Documents</title></head>' >> deploy/index.html
        echo '<body>' >> deploy/index.html
        echo '<h1>Documents</h1>' >> deploy/index.html
        for file in deploy/*.pdf; do
          filename=$(basename "$file")
          echo "<a href=\"$filename\">$filename</a><br>" >> deploy/index.html
        done
        echo '</body></html>' >> deploy/index.html
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: deploy
        publish_branch: gh-pages
        allow_empty_commit: true
        enable_jekyll: false
        keep_files: false
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
    - name: Clean up
      run: rm -rf deploy
